### PR TITLE
Support caller_is_root

### PR DESCRIPTION
**Pull request by olahfemi**
## Summary
Closes #_
- [x] n | Does it introduce breaking changes?
- [x] n | Is it dependant on the specific version of `cargo-contract` or `pallet-contracts`?

## Checklist before requesting a review
- [x] My code follows the style guidelines of this project
- [x] I have added an entry to `CHANGELOG.md`
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by cmichi** [comment]
Thanks for the PR, generally the right direction. The function should be implemented analog to `caller_is_origin`: https://github.com/use-ink/ink/blob/a0b2dceb0cdefb7ce6935a52620a8c139b43d4c4/crates/env/src/engine/on_chain/impls.rs#L672-L677. 

If you have full-text search the repository for `caller_is_origin` you'll find the other places where code needs to be added (`on_chain/impls.rs`).

**Comment by olahfemi** [comment]
@cmichi, [this](https://github.com/paritytech/polkadot-sdk/pull/3154#pullrequestreview-1858677540) suggests we don't need an integration test here. Can we merge now?

**Comment by cmichi** [comment]
@olahfemi Can you merge `master` and ensure that the PR only contains relevant changes? Right now it shows this: 
image
And from a quick glance there seem to be a number of unrelated changes in here.

**Comment by olahfemi** [comment]
> @olahfemi Can you merge `master` and ensure that the PR only contains relevant changes? Right now it shows this: image And from a quick glance there seem to be a number of unrelated changes in here.

I guess most of the changes are from when I merged master in the past and/or when I replaced the `Cargo,lock`. I'll look into it though.

**Comment by cmichi** [comment]
Superseded by https://github.com/use-ink/ink/pull/2332.

**Pull request closed without merging**
