### PR TITLE
Adds support for 'caller_is_root'

### PR DESCRIPTION
**Pull request by olahfemi**
## Summary
Closes #_
- [x] n | Does it introduce breaking changes?
- [x] n | Is it dependant on the specific version of `cargo-contract` or `pallet-contracts`?

This PR aims to add support for the `caller_is_root` function as requested by this [issue](https://github.com/use-ink/ink/issues/2096)

## Description

Since the `caller_is_root` function is similar to `caller_is_origin`, I looked for places where the latter was implemented and did the same for the former.

## Checklist before requesting a review
- [x] My code follows the style guidelines of this project
- [x] I have added an entry to `CHANGELOG.md`
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by olahfemi** [comment]
@cmichi Re: your [comment](https://github.com/use-ink/ink/pull/2310#issuecomment-2514212696):
I couldn't find SHA id of the commit that made many of the unrelated changes in my local log, so I created a new PR.

**Comment by cmichi** [comment]
@olahfemi There are some CI errors due to an unclosed delimiter. You can check [this guide](https://github.com/use-ink/ink/blob/master/CONTRIBUTING.md#checklist) on how to run what the CI does locally.

**Comment by olahfemi** [comment]
> @olahfemi There are some CI errors due to an unclosed delimiter. You can check [this guide](https://github.com/use-ink/ink/blob/master/CONTRIBUTING.md#checklist) on how to run what the CI does locally.

@cmichi, the unclosed delimiter has been fixed, and many of the local verification steps are passing now.

The failed steps weren't as a result of my changes. What do you want us to do about that?

Also, if my latest commit seems to have changed many unrelated files, it's because of the master merge and local verification.

**Comment by cmichi** [comment]
It's likely that you are using a different nightlyv version locally to execute the `cargo +nightly fmt --all`. Could you try 

```
rustup update nightly
cargo +nightly fmt --all
```

And push the changes?

**Comment by cmichi** [comment]
Alternatively: can you allow me to edit your PR as described [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)?

**Comment by olahfemi** [comment]
I've updated the nightly version, reran fmt and pushed the changes. Also, maintainers have edit access to the PR, so you can make edits if necessary.

**Pull request merged**
